export type CertificateData = {
  hash: string;
  label: string;
  owner: string;
  stacksBlock: number;
  burnBlock: number;
  timestamp: string;
  contractName: string;
  verifyUrl: string;
};

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

export function generateCertificate(data: CertificateData): string {
  const hash = escapeHtml(data.hash);
  const label = escapeHtml(data.label || "(none)");
  const owner = escapeHtml(data.owner);
  const stacksBlock = escapeHtml(String(data.stacksBlock));
  const burnBlock = escapeHtml(String(data.burnBlock));
  const timestamp = escapeHtml(data.timestamp);
  const contractName = escapeHtml(data.contractName);
  const verifyUrl = escapeHtml(data.verifyUrl);

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>ThesisLock Anchor Certificate</title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<style>
  *,*::before,*::after{box-sizing:border-box}
  html,body{margin:0;padding:0}
  body{
    background:#f4f4f5;
    color:#18181b;
    font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;
    line-height:1.5;
    padding:40px 16px;
  }
  .sheet{
    max-width:780px;
    margin:0 auto;
    background:#ffffff;
    border:1px solid #d4d4d8;
    border-radius:8px;
    overflow:hidden;
    box-shadow:0 1px 2px rgba(0,0,0,0.04);
  }
  .header{
    background:#0a0a0a;
    color:#fafafa;
    padding:32px 40px;
    border-bottom:4px solid #f59e0b;
  }
  .header h1{
    margin:0 0 6px;
    font-size:24px;
    font-weight:600;
    letter-spacing:-0.01em;
  }
  .header p{
    margin:0;
    font-size:13px;
    color:#a1a1aa;
    letter-spacing:0.02em;
  }
  .body{padding:32px 40px}
  .field{margin-bottom:20px}
  .field:last-child{margin-bottom:0}
  .label{
    display:block;
    font-size:11px;
    font-weight:600;
    color:#71717a;
    text-transform:uppercase;
    letter-spacing:0.08em;
    margin-bottom:4px;
  }
  .value{
    font-size:14px;
    color:#18181b;
    word-break:break-all;
  }
  .mono{font-family:ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,"Liberation Mono","Courier New",monospace;font-size:13px}
  .row{display:flex;gap:32px;flex-wrap:wrap}
  .row .field{flex:1 1 200px;margin-bottom:20px}
  .verify-box{
    margin-top:24px;
    padding:16px;
    background:#fafafa;
    border:1px solid #e4e4e7;
    border-radius:6px;
  }
  .verify-box a{
    color:#2563eb;
    text-decoration:underline;
    word-break:break-all;
    font-size:13px;
  }
  .footer{
    padding:20px 40px;
    background:#fafafa;
    border-top:1px solid #e4e4e7;
    font-size:11px;
    color:#71717a;
    text-align:center;
    line-height:1.6;
  }
  .footer a{color:#52525b;text-decoration:none}
  @media print{
    body{background:#ffffff;padding:0}
    .sheet{border:none;box-shadow:none}
  }
</style>
</head>
<body>
  <div class="sheet">
    <div class="header">
      <h1>ThesisLock Anchor Certificate</h1>
      <p>Proof of Document Existence on Stacks Blockchain</p>
    </div>
    <div class="body">
      <div class="field">
        <span class="label">Document Hash (SHA-256)</span>
        <div class="value mono">${hash}</div>
      </div>
      <div class="field">
        <span class="label">Label</span>
        <div class="value mono">${label}</div>
      </div>
      <div class="field">
        <span class="label">Anchored By</span>
        <div class="value mono">${owner}</div>
      </div>
      <div class="row">
        <div class="field">
          <span class="label">Stacks Block</span>
          <div class="value mono">${stacksBlock}</div>
        </div>
        <div class="field">
          <span class="label">Bitcoin Block</span>
          <div class="value mono">${burnBlock}</div>
        </div>
      </div>
      <div class="row">
        <div class="field">
          <span class="label">Contract</span>
          <div class="value mono">${contractName}</div>
        </div>
        <div class="field">
          <span class="label">Certificate Generated</span>
          <div class="value mono">${timestamp}</div>
        </div>
      </div>
      <div class="verify-box">
        <span class="label">Verify</span>
        <a href="${verifyUrl}">${verifyUrl}</a>
      </div>
    </div>
    <div class="footer">
      This certificate was generated by ThesisLock
      (<a href="https://thesis-lock.vercel.app">thesis-lock.vercel.app</a>).
      Verify on-chain at the URL above.
    </div>
  </div>
</body>
</html>`;
}
